export const Strings = {
    amount: "Amount",
    date: 'Date',
    expense: "Expense",
    income: "Income",
    addCategory: "Add category",
    category: "Category",
    viewCategory: "View category",
    seeAll: "See all",
    addIncome: "Add income",
    editIncome: "Edit income",
    name: "Name",
    noMoreItem: "No more item",
    editCategory: "Edit category",
    updateCategory: "Update category",
    notes: "Notes",
    updateIncome: "Update Income",
    description: "Description",
    categoryName: "Category name",
    categoryType: "Category type",
    monthlyExpense: "Monthly expense",
    categoryIcon: "Category icon",
    monthlyIncome: "Mothly Income",
    month: "Month",
    monthlyExpenseVsIncome: "Montly expense vs income",
    time: 'Time',
    viewIncome: 'View income'
}